import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api/client';
import DataTable, { type Column } from '../components/DataTable';
import type { Book, Member } from '../types';

const columns: Column<Book>[] = [{ header: 'Title', cell: (book) => <><strong>{book.title}</strong><small>{book.author}</small></> }, { header: 'Genre', cell: (book) => book.genre }, { header: 'ISBN', cell: (book) => book.isbn }, { header: 'Copies', cell: (book) => <span className={book.availableCopies ? '' : 'unavailable'}>{book.availableCopies} / {book.totalCopies}</span> }];
const memberColumns: Column<Member>[] = [{ header: 'Member', cell: (member) => <><strong>{member.name}</strong><small>{member.email}</small></> }, { header: 'Membership ID', cell: (member) => member.membershipId }, { header: 'History', cell: (member) => <Link to={`/members/${member._id}/history`}>View history</Link> }];
export default function Books() { const [books, setBooks] = useState<Book[]>([]); const [members, setMembers] = useState<Member[]>([]); const [search, setSearch] = useState(''); const [genre, setGenre] = useState(''); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const timer = setTimeout(() => { setLoading(true); api.getBooks({ page, limit: 10, search, genre }).then(({ data }) => { setBooks(data.data); setPages(data.pagination.totalPages || 1); }).catch((e) => setError(e.response?.data?.message || 'Could not load books.')).finally(() => setLoading(false)); }, 250); return () => clearTimeout(timer); }, [page, search, genre]);
  useEffect(() => { api.getMembers().then(({ data }) => setMembers(data.data)).catch(() => undefined); }, []);
  function changeFilter(setter: (value: string) => void, value: string) { setter(value); setPage(1); }
  return <><section className="page-title"><div><h1>Library catalogue</h1><p>Search availability and manage circulation.</p></div><Link className="button" to="/issue">Issue a book</Link></section><section className="toolbar"><input placeholder="Search by title" value={search} onChange={(e) => changeFilter(setSearch, e.target.value)} /><input placeholder="Filter by genre" value={genre} onChange={(e) => changeFilter(setGenre, e.target.value)} /></section>{error ? <div className="notice error">{error}</div> : loading ? <p className="loading">Loading books…</p> : <DataTable columns={columns} rows={books} emptyMessage="No books match your search." />}<div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page === pages} onClick={() => setPage(page + 1)}>Next</button></div><section className="members"><h2>Members</h2><DataTable columns={memberColumns} rows={members} emptyMessage="No registered members." /></section></>; }
