import { type FormEvent, useEffect, useState } from 'react';
import { api, getApiErrorMessage } from '../api/client';
import type { Book, Member } from '../types';

export default function IssueBook() {
  const [books, setBooks] = useState<Book[]>([]); const [members, setMembers] = useState<Member[]>([]); const [bookId, setBookId] = useState(''); const [memberId, setMemberId] = useState(''); const [dueDate, setDueDate] = useState('');
  const [loadingOptions, setLoadingOptions] = useState(true); const [submitting, setSubmitting] = useState(false); const [feedback, setFeedback] = useState(''); const [error, setError] = useState('');
  const loadOptions = async () => { setLoadingOptions(true); setError(''); try { const [booksResponse, membersResponse] = await Promise.all([api.getBooks({ page: 1, limit: 100 }), api.getMembers()]); setBooks(booksResponse.data.data); setMembers(membersResponse.data.data); } catch (err: unknown) { setError(getApiErrorMessage(err, 'Could not load books and members.')); } finally { setLoadingOptions(false); } };
  useEffect(() => { void loadOptions(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!bookId || !memberId) { setError('Select both a member and a book.'); return; } setSubmitting(true); setError(''); setFeedback(''); try { await api.issueBook(bookId, memberId, dueDate || undefined); setFeedback('Book issued successfully.'); setBookId(''); setMemberId(''); setDueDate(''); await loadOptions(); } catch (err: unknown) { setError(getApiErrorMessage(err, 'Could not issue the book.')); } finally { setSubmitting(false); } }
  if (loadingOptions) return <p className="loading">Loading books and members...</p>;
  return <section className="form-page"><h1>Issue a Book</h1><p>Assign an available book to a registered member.</p><form className="card issue-form" onSubmit={submit}>{feedback && <div className="notice success">{feedback}</div>}{error && <div className="notice error">{error}{!submitting && books.length === 0 && <button className="retry" type="button" onClick={() => void loadOptions()}>Retry</button>}</div>}<label>Member<select value={memberId} onChange={(event) => setMemberId(event.target.value)} disabled={submitting} required><option value="">Choose a member</option>{members.map((member) => <option key={member._id} value={member._id}>{member.name} ({member.membershipId})</option>)}</select></label><label>Book<select value={bookId} onChange={(event) => setBookId(event.target.value)} disabled={submitting} required><option value="">Choose an available book</option>{books.filter((book) => book.availableCopies > 0).map((book) => <option key={book._id} value={book._id}>{book.title} — {book.availableCopies} available</option>)}</select></label><label>Due Date <span className="muted">(optional; defaults to 14 days)</span><input type="date" value={dueDate} min={new Date().toISOString().slice(0, 10)} onChange={(event) => setDueDate(event.target.value)} disabled={submitting} /></label><button disabled={submitting || !bookId || !memberId}>{submitting ? 'Issuing...' : 'Issue Book'}</button></form></section>;
}
